language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

sudo: required
#env: #Environment Variables

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#install: true # You can skip the installation step entirely
before_install: scripts/pre_install.sh
install: gradle check --stacktrace

# before_script:
# script:

# In both after_failure and after_success, you can access the build result using the $TRAVIS_TEST_RESULT environment variable.
# after_success:
# after_failure:

# before_deploy: #OPTIONAL
# deploy: #OPTIONAL
# after_deploy: #OPTIONAL

# after_script:
