language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
 - java -version
 - gradle -version
 - gradle wrapper
 - echo "Prevent './gradlew assemble' from being executed."
 - ./gradlew -version
 - ./gradlew clean assemble --stacktrace

script:
 - ./gradlew clean assemble check --stacktrace
 - sonar-scanner -Dsonar.login=$SONAR_TOKEN

addons:
  sonarqube: true
